function addButton(parent,Label,callback,left,bottom)
    %Set Standard Height
    buttonHeight = 25;
    buttonWidth = 150;
    fontSize = 10;
    
    %Create Label for textbox
    uicontrol('Parent',parent,...
        'Style','pushbutton',...
        'HorizontalAlignment','right',...
        'String',Label,...
        'FontSize',fontSize,...
        'Units','pixels',...
        'Position',[left bottom buttonWidth buttonHeight],...
        'Callback',callback)