function addTextbox(parent,Tag,Label,left,bottom)
    %Set Standard Height
    height = 25;
    LabelWidth = 100;
    fontSize = 10;
    
    %Create Label for textbox
    tb = uicontrol('Parent',parent,...
        'Style','text',...
        'Tag',Tag,...
        'HorizontalAlignment','right',...
        'String',Label,...
        'FontSize',fontSize,...
        'Units','pixels',...
        'Position',[left bottom LabelWidth height]);
    
    %Get Limits for textbox
    pad = 0.02; %Padding between text box and label
    tb.Units = 'normalized';
    left = sum(tb.Position([1 3])) + pad;
    width = 1 - left - pad;
    
    %Create Textbox
    ed = uicontrol('Parent',parent,...
        'Style','edit',...
        'Tag',Tag,...
        'HorizontalAlignment','left',...
        'Units','normalized',...
        'FontSize',fontSize,...
        'Position',[left .1 width .1]);
    
    %Switch back to pixels to set bottom and height
    ed.Units = 'pixels';
    ed.Position([2 4]) = [bottom height];
    