function h = figureGUI(title,Size)
    %Returns a figure configured to be used as in a GUI
    h = figure('NumberTitle','off',...
        'Name',title,...
        'Toolbar','none',...
        'MenuBar','none',...
        'Visible','off',...
        'Resize','off',...
        'Units','normalized',...
        'Position',[0 0 1 1]);
    
    %Find Screen Size
    h.Units = 'pixels';
    ScreenSize = h.Position(3:4);
    
    %Resize and Center on screen
    h.Position(1:2) = (ScreenSize - Size)/2;
    h.Position(3:4) = Size;
end